# Generated by Django 4.2.6 on 2023-11-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='video/img')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
