# Generated by Django 4.2.6 on 2023-11-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='kament/img')),
            ],
        ),
        migrations.CreateModel(
            name='Remot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='remot/img')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
